blank_issues_enabled: false
contact_links:
  - name: Question or usage help
    url: https://github.com/MrAdex77/google-play-scraper/discussions
    about: Ask questions and discuss usage in Discussions.
