import * as z from 'zod/mini';

export const appCategorySchema = z.object({
  name: z.string(),
  id: z.nullable(z.string()),
});

export type AppCategory = z.infer<typeof appCategorySchema>;

const histogramSchema = z.object({
  '1': z.number(),
  '2': z.number(),
  '3': z.number(),
  '4': z.number(),
  '5': z.number(),
});

export const appSchema = z.object({
  title: z.string(),
  description: z.string(),
  descriptionHTML: z.string(),
  summary: z.optional(z.string()),
  installs: z.optional(z.string()),
  minInstalls: z.optional(z.number()),
  maxInstalls: z.optional(z.number()),
  score: z.optional(z.number().check(z.gte(0), z.lte(5))),
  scoreText: z.optional(z.string()),
  ratings: z.optional(z.number()),
  reviews: z.optional(z.number()),
  histogram: histogramSchema,
  price: z.number(),
  originalPrice: z.optional(z.number()),
  discountEndDate: z.optional(z.number()),
  free: z.boolean(),
  currency: z.optional(z.string()),
  priceText: z.string(),
  available: z.boolean(),
  offersIAP: z.boolean(),
  IAPRange: z.optional(z.string()),
  androidVersion: z.string(),
  androidVersionText: z.string(),
  androidMaxVersion: z.string(),
  developer: z.string(),
  developerId: z.string(),
  developerEmail: z.optional(z.string()),
  developerWebsite: z.optional(z.string()),
  developerAddress: z.optional(z.string()),
  developerLegalName: z.optional(z.string()),
  developerLegalEmail: z.optional(z.string()),
  developerLegalAddress: z.optional(z.string()),
  developerLegalPhoneNumber: z.optional(z.string()),
  privacyPolicy: z.optional(z.string()),
  developerInternalID: z.string(),
  genre: z.string(),
  genreId: z.string(),
  categories: z.array(appCategorySchema),
  icon: z.string(),
  headerImage: z.optional(z.string()),
  screenshots: z.array(z.string()),
  video: z.optional(z.string()),
  videoImage: z.optional(z.string()),
  previewVideo: z.optional(z.string()),
  contentRating: z.optional(z.string()),
  contentRatingDescription: z.optional(z.string()),
  adSupported: z.boolean(),
  released: z.optional(z.string()),
  updated: z.number(),
  version: z.string(),
  recentChanges: z.optional(z.string()),
  comments: z.array(z.string()),
  preregister: z.boolean(),
  earlyAccessEnabled: z.boolean(),
  isAvailableInPlayPass: z.boolean(),
  appId: z.string(),
  url: z.string(),
});

export type App = z.infer<typeof appSchema>;
